### ISSUE TITLE
Got error when create Topic/Schema on UI

### ISSUE THREAD

**Issue by allenzhangliugen** [datafibers-community/df_data_service#159]
On DF-Demo UI, when create a new Topic, the icon on the right top corner keeps circling. There is error message on the back end log.

```
2017-10-23 00:24:27 [DEBUG] SchemaRegisterProcessor:201  - Schema|subject|compatibility: {"name":"ST4","type":"record","fields":[{"name":"Name","type":"string"}]}|ST4|FULL
2017-10-23 00:24:27 [DEBUG] SchemaRegisterProcessor:237  - Schema object.toString(): {"schema":"{\"name\":\"ST4\",\"type\":\"record\",\"fields\":[{\"name\":\"Name\",\"type\":\"string\"}]}"}
2017-10-23 00:24:27 [DEBUG] SchemaRegisterProcessor:273  - Compatibility object2.toString(): {"compatibility":"FULL"}
2017-10-23 00:24:27 [ERROR] KafkaThread            :43   - Uncaught exception in kafka-admin-client-thread | adminclient-1:
org.apache.kafka.common.protocol.types.SchemaException: Error computing size for field 'create_topic_requests': Error computing size for field 'topic': Missing value for field 'topic' which has no default value.
        at org.apache.kafka.common.protocol.types.Schema.sizeOf(Schema.java:93)
        at org.apache.kafka.common.protocol.types.Struct.sizeOf(Struct.java:258)
        at org.apache.kafka.common.requests.AbstractRequestResponse.serialize(AbstractRequestResponse.java:28)
        at org.apache.kafka.common.requests.AbstractRequest.serialize(AbstractRequest.java:81)
        at org.apache.kafka.common.requests.AbstractRequest.toSend(AbstractRequest.java:74)
        at org.apache.kafka.clients.NetworkClient.doSend(NetworkClient.java:396)
        at org.apache.kafka.clients.NetworkClient.doSend(NetworkClient.java:370)
        at org.apache.kafka.clients.NetworkClient.send(NetworkClient.java:332)
        at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.sendEligibleCalls(KafkaAdminClient.java:767)
        at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.run(KafkaAdminClient.java:919)
```

**Comment by datafibers** [comment]
fixed. @allenzhangliugen pls. test it

**Comment by datafibers** [comment]
tested during demo. Close it once merged

**Comment by datafibers** [comment]
merged close
